### ISSUE TITLE
Request: Edit the values of entries in list

### ISSUE THREAD

**Issue by berto-dev** [ChrisLauinger77/XES-Settings-Center-Extension#10]
Like the title.

I would like to be able to edit the constructed and saved entries, currently there seems to be no such possibility

It would be convenient to put an "update" or "edit" button

**Comment by berto-dev** [comment]
Premise that it's a greate helper and it's all a simple suggestion 

I need always to update or check what it do... It's a simple part of CRUD of any application and It's totally normal if you need to make your shortcut 😅

An exemple: I make my shorthand cli for update wifi and other and i cant update or get again what i did for all necessary testing. Every X days I need to update it in the 50% of cases and...  I completely lost it!! It's a greate limitation that I can't read and mod what is inside the asset. It's really terrible, like incomplete app.

**Comment by ChrisLauinger77** [comment]
You can do a script for your usecase and rather then edit the entry just edit the script.

**Comment by berto-dev** [comment]
The script is into the entry, the entry is the script.
Now i (or better, everyone) can't mod or view the script and the entry so, you only link a scripts path or you set for your users a CRUD for the entries... it's your choose man.

bye!
