### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Ticklezz** [ChrisLauinger77/XES-Settings-Center-Extension#4]
Does the icon have a purpose? Can it be removed? Is it telling me something is wrong? I am referring to the one generated by your amazing extension. 
![Screenshot from 2023-01-08 01-25-58](https://user-images.githubusercontent.com/113319295/211185340-a93613e4-eb6c-4566-94a9-fd97c647f89e.png)

**Comment by ChrisLauinger77** [comment]
Glad you like the extension.
Well for me it looks different:
![Bildschirmfoto vom 2023-01-08 10-14-43](https://user-images.githubusercontent.com/3518684/211188638-da475c98-507b-47b7-95d9-5682de26e89e.png)
It indicated that the extension is loaded. I am not sure if it can be removed. It did not bother me to be honest.

**Comment by ChrisLauinger77** [comment]
It should look like this (after my change):
![Bildschirmfoto vom 2023-01-08 10-28-06](https://user-images.githubusercontent.com/3518684/211189149-d4770094-bfaa-4571-8c0e-bb7d33e86a86.png)
For you even the wrong icon from before did not show - so I think you miss a package from your distro.
for me (debian) the icons come with "adwaita-icon-theme" package
https://packages.debian.org/search?keywords=adwaita-icon-theme

**Comment by Ticklezz** [comment]
> 

I am using Kora icons. If I could disable it that would be wonderful. I enjoy the extra minimalist feel.

**Comment by ChrisLauinger77** [comment]
pls let me know how it looks 4 u after my change

**Comment by ChrisLauinger77** [comment]
I made my self an enhancement issue #5
