### ISSUE TITLE
Make showing the systemindicator configurable in gsettings

### ISSUE THREAD

**Issue by ChrisLauinger77** [ChrisLauinger77/XES-Settings-Center-Extension#5]
![Bildschirmfoto vom 2023-01-08 10-51-59](https://user-images.githubusercontent.com/3518684/211189815-030dd4b9-c37d-44de-8dfe-be8aba330c55.png)
The settingscenter icon should be able to be hidden over a gsettings option

**Comment by Ticklezz** [comment]
Amazing!!
