### ISSUE TITLE
Extension preferences

### ISSUE THREAD

**Issue by Ticklezz** [ChrisLauinger77/XES-Settings-Center-Extension#6]
What am I missing here? Is it intended to open extensions manager? I have the flatpak installed.
![Screenshot from 2023-01-08 15-21-07](https://user-images.githubusercontent.com/113319295/211219856-e1d117f1-c372-4706-b533-aee93e17d4f0.png)

**Comment by ChrisLauinger77** [comment]
Where exactly are you getting this message ? Do you click on the Settings entry of SettingsCenter menu last item ?
What is the complete error message ? In the screenshot it is cut. Hard to tell whats wrong.

**Comment by Ticklezz** [comment]
Sorry about that. Here is what is and I guess I did not have that installed. I am on gnome 43.1. I cannot seem to locate the package for it. Sorry for my ignorance.
![Screenshot from 2023-01-08 18-53-39](https://user-images.githubusercontent.com/113319295/211227467-240291f1-2ef6-4a78-9bff-8114be624d5e.png)


![Screenshot from 2023-01-08 18-46-10](https://user-images.githubusercontent.com/113319295/211227422-1d2673d7-face-4294-be68-ed6abe0e142f.png)

**Comment by Ticklezz** [comment]
> Where exactly are you getting this message ? Do you click on the Settings entry of SettingsCenter menu last item ? What is the complete error message ? In the screenshot it is cut. Hard to tell whats wrong. is this package installed ? gnome-shell-extension-prefs (https://packages.debian.org/bookworm/gnome-shell-extension-prefs)

It was when pressing the extension preferences button.

**Comment by Ticklezz** [comment]
I found the correct package. You did point me in the right direction.

**Comment by ChrisLauinger77** [comment]
> I found the correct package. You did point me in the right direction.

As you never told me the distro you use - I can only point at the package of the distro I use ...
