### ISSUE TITLE
Latest gnome shell internal changes broke extension code on gnome 45

### ISSUE THREAD

**Issue by ionutbortis** [ChrisLauinger77/XES-Settings-Center-Extension#9]
Hello,

While updating my extension to 45 I also installed this extension in order to test along with the Quick Settings toggles.

It seems that this [commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/93b89ce0c5c64a0770ea51120dc2326c1b3863ab?view=parallel) is breaking your extension's code because they removed the `_addItems` method:

```
(gnome-shell:4346): Gjs-WARNING **: 13:00:01.486: JS ERROR: Extension SettingsCenter@lauinger-clan.de: TypeError: QuickSettingsMenu._addItems is not a function
_init@file:///home/ionut/.local/share/gnome-shell/extensions/SettingsCenter@lauinger-clan.de/extension.js:113:31
SystemIndicator@resource:///org/gnome/shell/ui/quickSettings.js:833:1
SettingsCenterIndicator@file:///home/ionut/.local/share/gnome-shell/extensions/SettingsCenter@lauinger-clan.de/extension.js:91:5
enable@file:///home/ionut/.local/share/gnome-shell/extensions/SettingsCenter@lauinger-clan.de/extension.js:133:27
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:250:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:454:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:724:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:730:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:765:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:69:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:290:22
start@resource:///org/gnome/shell/ui/main.js:163:11
@resource:///org/gnome/shell/ui/init.js:11:47
@resource:///org/gnome/shell/ui/init.js:21:20

```

The above mentioned commit is not yet released, but it is merged to their main branch. I observed this because I've built the latest code inside a vm in order to have the [latest changes](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2894) related to Quick Settings.

They recommend now for extensions to use the new `addExternalIndicator` method from `panel.js`.

I gues your code from `extension.js`:
```
// Add the indicator to the panel and the toggle to the menu
QuickSettingsMenu._indicators.add_child(this);
QuickSettingsMenu._addItems(this.quickSettingsItems);
```

would change to something like this:
```
// Add the indicator to the panel and the toggle to the menu
QuickSettingsMenu.addExternalIndicator(this);
```

This new method also takes care of adding the toggle before the background apps section.

Just Perfection mentioned on the matrix channel that we should test the new ego submissions on an official build (proper release candidate) of gnome shell. So I guess that means we should wait for gnome os or fedora rawhide to push the latest 45 build.

HTH,
Ionut

**Comment by ChrisLauinger77** [comment]
Thx you for letting me know.
2 of my extensions are affected with this - I test all of my extensions with GNOME OS nightly.
I will monitor when they break.
